source 'http://rubygems.org'

gem 'wagn', :path=>'/usr/cldstr/wagn.org/wagn/ws/wagn-gem'

gem 'therubyracer'

gem 'mysql2'

gem 'dalli'

Dir.glob(File.join(File.dirname(__FILE__), 'mod','**{,/*/**}','Gemfile')).each do |gemfile|
  instance_eval(File.read(gemfile))
end