source 'http://rubygems.org'

gem 'wagn', ">= 1.14.2"

gem 'therubyracer'

gem 'mysql2'

gem 'dalli'

Dir.glob(File.join(File.dirname(__FILE__), 'mod','**{,/*/**}','Gemfile')).each do |gemfile|
  instance_eval(File.read(gemfile))
end