=begin
if ENV['BUNDLE_GEMFILE'] =~ /cldstr/
  gem 'rufus-scheduler', :path=>'/usr/cldstr/wagn.org/wagn-aikidoart/ws/email_remote_control/gems/ruby/1.9.1/gems/rufus-scheduler-3.0.9/'
else
  gem 'rufus-scheduler'
end
=end